---
# Documentation: https://github.com/probot/stale
daysUntilStale: 180
daysUntilClose: 14
exemptLabels:
  - bug
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs during
  the next 14 days. Thanks for your contribution.
closeComment: >
  This issue has been automatically closed because it has not had recent
  activity.
