---
version: 1
builder:
  configs:
    - platform: ios
      documentation_targets: [
        PillarboxAnalytics,
        PillarboxCircumspect,
        PillarboxCore,
        PillarboxCoreBusiness,
        PillarboxPlayer
      ]
