---
version: 1
builder:
  configs:
    - platform: ios
      documentation_targets: [
        PillarboxPlayer,
        PillarboxStandardConnector,
        PillarboxCoreBusiness,
        PillarboxMonitoring,
        PillarboxAnalytics,
        PillarboxCore,
        PillarboxCircumspect
      ]
