---
included:
  - Demo
  - Plugins
  - Sources
  - Tests

excluded:
  - ./**/Package.swift
  - ./**/*.docc

disabled_rules:
  - accessibility_label_for_image
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - discouraged_none_name
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - file_name
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - identifier_name
  - indentation_width
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - number_separator
  - no_empty_block
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - nslocalizedstring_require_bundle
  - one_declaration_per_file
  - required_deinit
  - sorted_enum_cases
  - statement_position
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_else
  - todo
  - vertical_whitespace_between_cases
  - yoda_condition

opt_in_rules:
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - function_body_length
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - non_overridable_class_declaration
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_key_path
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - private_swiftui_state
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - self_in_property_initialization
  - shorthand_argument
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_body_length
  - type_contents_order
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

attributes:
  always_on_same_line: ["@Environment"]

cyclomatic_complexity:
  warning: 5
  error: 8

file_header:
  required_pattern: |
    \/\/
    \/\/  Copyright \(c\) SRG SSR. All rights reserved.
    \/\/
    \/\/  License information is available from the LICENSE file.

file_length:
  warning: 1000
  error: 1500

function_parameter_count:
  warning: 8

line_length:
  warning: 160
  error: 200

missing_docs:
  excludes_inherited_types: false

nesting:
  type_level: 2

type_name:
  allowed_symbols: "`"
