included:
  - Demo
  - Sources
  - Tests

disabled_rules:
    - cyclomatic_complexity
    - identifier_name
    - file_length
    - force_cast
    - force_try
    - function_body_length
    - line_length
    - multiple_closures_with_trailing_closure
    - statement_position
    - todo
    - type_body_length

trailing_whitespace:
  ignores_empty_lines: true
  severity: warning

type_name:
  excluded:
    - Id

function_parameter_count:
  warning: 8

nesting:
  type_level: 2

