---
name: 💭 Question
description: Ask us for guidance or help.
labels: ["question", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Can your answer be found elsewhere?
      options:
        - label: >
            I have searched existing
            [issues](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aquestion+)
            and found no similar question.
          required: true
        - label: >
            I have browsed the available documentation and found no answer
            to my question.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed question
      description: Please develop your question in further detail.
    validations:
      required: true
