#!/bin/sh

#================================================================
# Quality check
#================================================================

PATH="/opt/homebrew/opt/ruby/bin:$PATH"

if make check-quality; then
  echo "✅ Quality checked"
else
  echo "❌ Quality check failed"
  exit 1
fi
