#!/bin/sh

#================================================================
# Quality check
#================================================================

PATH="/opt/homebrew/bin:/opt/homebrew/opt/ruby/bin:$PATH"

if make pre-commit; then
  echo "✅ Quality checked"
else
  echo "❌ Quality check failed"
  exit 1
fi
