#!/bin/sh

#================================================================
# Quality check
#================================================================

PATH="$(which swiftlint):$(which ruby):$PATH"

if Scripts/check-quality.sh; then
	echo "✅ Quality checked"
else
	echo "❌ Quality check failed"
	exit 1
fi
