---
name: CI

on:  # yamllint disable-line rule:truthy
  merge_group:
  pull_request:

jobs:
  check-quality:
    name: 🔎 Check quality
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #  v6.0.2

      - name: Run the quality check
        run: make check-quality

  tests:
    name: 🧪 Tests
    runs-on: macos-26
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform: [ios, tvos]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #  v6.0.2

      - name: Run tests
        run: make test-${{ matrix.platform }}

      - name: Publish report
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386  #  v6.4.0
        if: always()
        with:
          report_paths: 'fastlane/test_output/*.xml'
          check_name: 📋 Unit test report (${{ matrix.platform }})
          fail_on_failure: true

  build-demos:
    name: 🔨 Builds
    runs-on: macos-26
    strategy:
      matrix:
        platform: [ios, tvos]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #  v6.0.2

      - name: Build the demo
        run: make build-${{ matrix.platform }}
